version: "3.8"

networks:
  items_docker_net:
    driver: bridge

services:

  items-auth:
    build:
      context: .
      dockerfile: Dockerfile.auth
    container_name: items-auth
    ports:
      - "3030:3030"
    networks:
      - items_docker_net

  items-cms:
    build:
      context: .
      dockerfile: Dockerfile.cms
    container_name: items-cms
    ports:
      - "2222:2222"
    networks:
      - items_docker_net

  items-gateway-api:
    build:
      context: .
      dockerfile: Dockerfile.gateway-api
    container_name: items-gateway-api
    ports:
      - "2111:2111"
    networks:
      - items_docker_net

  items-web_portal:
    build:
      context: .
      dockerfile: Dockerfile.web_portal
    container_name: items-web_portal
    ports:
      - "2333:2333"
    networks:
      - items_docker_net
