name: Build | Oat++ Docker Image
on:
  push:
    branches:
      - 'main'

  workflow_dispatch:
    inputs:
      push_to_registry:
        type: boolean
        description: Push to Registry
        required: true

jobs:
  build-images:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Checkout Intmac code
        uses: actions/checkout@v3

      - name: Determine current branch
        run: |
          if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
              echo "BUILD_TAG=intmac/intmac_oatcpp:LATEST" >> "$GITHUB_ENV"
          else
              echo "BUILD_TAG=intmac/intmac_oatcpp:${GITHUB_REF##*/}" >> "$GITHUB_ENV"
          fi

      - name: Build and push Oat++ library Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/Dockerfile.oatcpp_image
          push: ${{ inputs.push_to_registry }}
          no-cache: true
          tags: ${{ env.BUILD_TAG }}
          platforms: |
              linux/arm64
              linux/amd64
