name: Build ServiceFramework Docker Image
on:
  push:
    branches:
      - 'master'
      - 'cpluplus_restart'

  workflow_dispatch:
    inputs:
      push_to_registry:
        type: boolean
        description: Push to Registry
        required: true

jobs:
  build-images:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Checkout Intmac code
        uses: actions/checkout@v3

      - name: Determine current branch
        run: |
          if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
              echo "BUILD_TAG=LATEST" >> "$GITHUB_ENV"
          else
              echo "----- BUILDING ON BRANCH -----"
              echo "BUILD_TAG=${GITHUB_REF##*/}" >> "$GITHUB_ENV"
          fi

      - name: Display current build tag
        run: echo "BUILD TAG = $BUILD_TAG | GITHUB_ENV = $GITHUB_REF"

      - name: Build and push Oat++ library Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/Dockerfile.oatcpp_image
          push: true
          no-cache: true
          tags: intmac/images:oatcpp-$BUILD_TAG
          platforms: |
              linux/arm64
              linux/amd64
