name: Build | Accounts Svc Docker
on:
  push:
    # Set branch to be invalid on purpose!
    branches:
      - 'invalid'

  workflow_dispatch:
    inputs:
      push_to_registry:
        type: boolean
        description: Push to Registry
        required: true

jobs:
  build-images:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
