name: Lint Accounts Microservice

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the development branch
on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install Requirements
      run: |
        python -m pip install --upgrade pip
        pip install cpplint
    - name: Execute Lint
      run: |
        cpplint --recursive --output=vs7 --root=src/itemsAccountsSvc src/itemsAccountsSvc