name: Gateway Svc Nightly Build
on:
    schedule:
     - cron: '0 1 * * *'

    workflow_dispatch:
     inputs:
       push_to_registry:
         type: boolean
         description: Push to Registry
         required: true
       image_to_build:
         type: choice
         description: Docker Images to Build
         default: 'ALL'
         options:
           - gateway
           - redis
           - ALL
jobs:
  build-images:
    runs-on: ubuntu-22.04
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v3
      -
        name: Build and push Gateway Docker Image
        if: ${{ (inputs.image_to_build == 'ALL') ||
                (inputs.image_to_build == 'gateway') ||
                (inputs.image_to_build == '') }}
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/Dockerfile.gateway_svc
          push: true
          no-cache: true
          tags: intmac/nightly:gateway-svc-nightly
          platforms: |
              linux/arm64
              linux/amd64
      -
        name: Build and push Gateway Redis Image
        if: ${{ (inputs.image_to_build == 'ALL') ||
                (inputs.image_to_build == 'redis') ||
                (inputs.image_to_build == '') }}
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/Dockerfile.sessions
          push: true
          no-cache: true
          tags: intmac/nightly:sessions-nightly
          platforms: |
              linux/arm64
              linux/amd64