name: Lint Auth Microservice

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the development branch
on:
  pull_request:
    branches:
      - main
      - project-restart
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install Requirements
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install jsonschema
        pip install quart
    - name: Run Pylint
      run: |
        cd items
        export PYTHONPATH=items/auth:items/shared
        pylint `pwd`/auth --rcfile=items/pylint-auth.rc
